app = "tcd-origin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "7860"

[[services]]
  internal_port = 7860
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 10
    soft_limit = 5

  [[services.ports]]
    port = 80

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
